pool: 

  name: Azure Pipelines 

variables: 

  SolutionName: ‘Logger’ 

steps: 

– task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@0 

  displayName: ‘Power Platform Tool Installer ‘ 

  inputs: 

    PowerAppsAdminVersion: 2.0.137 

    CrmSdkCoreToolsVersion: 9.1.0.90 

 

– task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@0 

  displayName: ‘Power Platform Export Solution ‘ 

  inputs: 

    authenticationType: PowerPlatformSPN 

    PowerPlatformSPN: CRM967032 

    SolutionName: ‘$(SolutionName)’ 

    SolutionOutputFile: ‘$(Build.ArtifactStagingDirectory)\$(SolutionName).zip’ 

 

– task: microsoft-IsvExpTools.PowerPlatform-BuildTools.unpack-solution.PowerPlatformUnpackSolution@0 

  displayName: ‘Power Platform Unpack Solution ‘ 

  inputs: 

    SolutionInputFile: ‘$(Build.ArtifactStagingDirectory)\$(SolutionName).zip’ 

    SolutionTargetFolder: ‘$(Build.SourcesDirectory)\$(SolutionName)’ 

 

– script: | 

   echo commit all changes 

   git config user.email “anbaard@gmail.com” 

   git config user.name “ancob85” 

   git checkout main 

   git add –all 

   git commit -m “solution init” 

   echo push code to new repo 

   git -c http.extraheader=”AUTHORIZATION: bearer $(System.AccessToken)” push origin main 

    

  displayName: ‘Command Line Script’ 